title: "Die Jäger und die Gejagten"
subtitle: "Eine Science-Fiction Gruselgeschichte über parasitäre Aliens, kosmische Gerechtigkeit und die Transformation der Menschheit"
author: "Draven Quantum"
isbn: ""
edition: "1. Auflage"
publisher: "Consciousness Publishing"
date: "2025"
language: "de"
description: "Was geschieht, wenn winzige, parasitäre Aliens die Menschheit übernehmen – und dann kosmische Polizei auftaucht, um sie zu stoppen?

Die Vak'tar sind mikroskopisch kleine Sadisten, die nachts durch Nase und Ohren in schlafende Menschen eindringen. Sie verwandeln ihre Wirte in grausame Monster, die ihre eigenen Familien angreifen und die Welt ins Chaos stürzen. Doch die Vak'tar sind Verbrecher – Ausgestoßene ihrer eigenen Spezies.

Dann kommen die Anari: Lichtwesen, die als kosmische Jäger diese parasitären Kriminellen durch das Universum verfolgen. Sie befreien die Menschheit, aber der Schaden ist bereits angerichtet. Als Wiedergutmachung heilen die Anari nicht nur die Traumata, sondern geben der Menschheit Technologien und Weisheit, die sie zu etwas Besserem machen, als sie je war.

Eine Geschichte über Widerstand, Heilung und die Frage: Was macht uns menschlich, wenn alles verloren scheint?

Folge Dr. Sarah Chen, der Hackerin Aida Ramić, dem Veteranen Daryl Mensah und anderen, die stark genug waren, den Parasiten zu widerstehen – und nun über den Frieden einer neuen Welt wachen."
keywords: 
  - Science Fiction
  - Horror
  - Aliens
  - Parasiten
  - Body Horror
  - Kosmische Gerechtigkeit
  - Transformation
  - Widerstand
  - Psychologischer Thriller
  - Utopie
  - Dystopie
  - Erste Kontakt
  - Neurologie
  - Bewusstsein
  - Heilung
  - Trauma
  - Technologie
  - Spiritualität
  - Menschlichkeit
  - Außerirdische Invasion
  - Lichtwesen
  - Neuronale Parasiten
  - Kosmischer Horror
  - Wissenschaft
  - Ethik
  - Erlösung
  - Wiedergutmachung
  - Charakterentwicklung
  - Ensemble Cast
  - Drei-Akt-Struktur
cover_image: "assets/covers/cover.jpg"
output_formats: 
  - pdf
  - epub
  - mobi
  - docx
kdp_enabled: true
